.github/workflows/build.yml, .github/workflows/format.yml, .github/workflows/test.yml
Enables CI tests on all branches. This makes working on branches easier.
=> CI: Test for pushes on all branches

src/linux/virtio.rs
remove typo to solve issue #17
=> fix check to notify output

Cargo.lock, Cargo.toml, src/debug_manager.rs, src/gdb_parser.rs, src/linux/gdb.rs, src/linux/uhyve.rs, src/linux/vcpu.rs, src/linux/virtio.rs, src/linux/virtqueue.rs, src/macos/gdb.rs, src/macos/ioapic.rs, src/macos/uhyve.rs, src/macos/vcpu.rs, src/shared_queue.rs, src/utils.rs, src/vm.rs
=> Refactor uhyve for rust edition 2018

src/consts.rs, src/lib.rs, src/linux/vcpu.rs, src/macos/vcpu.rs, src/main.rs, src/vm.rs
+ remove MAC_ADDRESS global state
=> Use library crate for uhyve binary

.travis.yml, Cargo.lock, Cargo.toml, benches_data/hello_world, src/vm.rs
- prepare uhyve to support relocatable unikernels
- in the future, only relocatable binaries are supported
=> add support of relocatable unikernels

Cargo.lock, Cargo.toml, src/vm.rs
- Rayon support was just a test
=> simplify code and remove rayon support

README.md
Hey, I faced this severe error while I was building. I tried doing everything and read many blogs but only after I came to know about this BIOS setup, it did work for me.
So, I thought of adding this as a note so that if someone faces difficulty, then might find this useful :)
=> Note on BIOS settings during Virtualization

src/bin/uhyve.rs
PR to solve issuer hermitcore/rusty-hermit#90
=> improve error message

README.md, app.entitlements, src/bin/uhyve.rs, src/macos/vcpu.rs, src/utils.rs
- remove also a bug in the IO-APIC emulation
- remove some compiler warnings
=> add support for macOS Big Sur

codecov.yml, src/bin/uhyve.rs, src/linux/uhyve.rs, src/linux/virtio.rs, src/macos/vcpu.rs, src/utils.rs, src/vm.rs
A valid exit code means that a thread calls the system call `exit`. In this case, we have to terminate all threads like the behaviour of `exit`. This current version is the reason that PR `hermitcore/libhermit-rs#160` doesn't pass all tests.
=> revise exit handling

src/bin/uhyve.rs
- the previous version carshed with a segmentation fault
- remove closure and use a common C function to store the dump file
=> revise creation of trace files

README.md, src/bin/uhyve.rs, src/debug_manager.rs, src/linux/gdb.rs, src/linux/uhyve.rs, src/macos/gdb.rs
This pull request fixes some typos.
=> fix a few typos

src/lib.rs, src/linux/vcpu.rs, src/macos/vcpu.rs, src/vm.rs
=> Let VirtualCPU::run always return exit code

benches/vm/mod.rs, src/bin/uhyve.rs, src/lib.rs, src/linux/uhyve.rs, src/macos/uhyve.rs, src/vm.rs, tests/common.rs
Depends on https://github.com/hermitcore/uhyve/pull/144
=> Rework high level run interface

.github/workflows/clippy.yml, bors.toml, rust-toolchain, rust-toolchain.toml, src/gdb_parser.rs, tests/fs-test.rs
This migrates to `rust-toolchain.toml` format to specify components and adds a Clippy workflow.
=> Add GitHub Action Clippy Workflow

src/macos/vcpu.rs
Faulty behavior introduced in https://github.com/hermitcore/uhyve/commit/fa62a6d6d1c11f2ec221143207a6b627005e1129#diff-9940bd2f66049a07423515adc7f6c054b3bb7bdd260b59b3b74e1f3007c0830cL680
Closes https://github.com/hermitcore/uhyve/pull/183
bors r+
=> macos: Fixup assertion

.github/workflows/test.yml
Closes https://github.com/hermitcore/uhyve/pull/206.
=> CI: Upgrade coverage action

src/paging.rs
Addresses https://github.com/hermitcore/rusty-hermit/issues/160.
=> Remove license headers

README.md
=> README: Add warning about host file sytem access

src/bin/uhyve.rs, src/linux/mod.rs, tests/test-kernels/Cargo.lock, tests/test-kernels/rust-toolchain.toml
Depends on
* https://github.com/hermitcore/rusty-hermit/issues/167
=> Integration Tests: Upgrade to recent nightly channel

.github/workflows/test.yml, rust-toolchain.toml
Closes https://github.com/hermitcore/uhyve/issues/247.
=> rust-toolchain.toml: Default to stable channel

src/vm.rs
Fixes https://github.com/hermitcore/uhyve/issues/272.
=> Support non UTF-8 kernel arguments

src/macos/aarch64/vcpu.rs
=> print also value of TTBR0 register

Cargo.lock, Cargo.toml, src/bin/uhyve.rs
Closes https://github.com/hermitcore/uhyve/pull/298.
=> Upgrade clap to 3.1

Cargo.lock, Cargo.toml, src/bin/uhyve.rs
Closes https://github.com/hermitcore/uhyve/pull/339.
=> Upgrade clap to 3.2

README.md
Closes https://github.com/hermitcore/uhyve/issues/344.
=> README: Update installation instructions

Cargo.lock, src/vm.rs, tests/common.rs, tests/test-kernels/.cargo/config.toml, tests/test-kernels/Cargo.lock, tests/test-kernels/Cargo.toml, tests/test-kernels/rust-toolchain.toml, tests/test-kernels/src/bin/gdb.rs
See
* https://github.com/hermitcore/hermit-entry/pull/4
=> Check entry version

src/vm.rs
=> Improved check of hermit-entry version to handle files without a note section

Cargo.lock, Cargo.toml, README.md
Closes https://github.com/hermitcore/uhyve/issues/435.
=> Release 0.2.1

tests/test-kernels/Cargo.lock, tests/test-kernels/Cargo.toml
Fixes the breaking tests due to https://github.com/hermitcore/libhermit-rs/issues/756
=> Bumped hermit-sys to 0.5

src/linux/uhyve.rs, src/linux/vcpu.rs
(A new implementation is in progress)
=> Removed old disfunctional and unused networking code.

.github/workflows/ci.yml
Closes https://github.com/hermit-os/uhyve/issues/664
=> ci: unpin codecov

uhyve-interface/src/parameters.rs
=> fix(uhyve-interface): don't use `std` without feature

LICENSE-APACHE
See https://github.com/rust-lang/rust/commit/2ccf65c7eba519dcc407cb76f08d04ac00d05851
Closes https://github.com/hermit-os/uhyve/issues/693
CC: @n0toose
=> chore: remove appendix fomr `LICENSE-APACHE`

src/mem.rs
As I was trying to understand how Uhyve interacts with the guest physical memory, I stumbled upon this function and entered a few test values.
I believe that this change might be good to check for regressions at best, especially because of the fact that this component is a dependency of test_virt_to_phys.
=> mem.rs: Extend test_mmap_memory_readwrite()

README.md
In the beginning, I found myself quite lost as I was not totally sure how to use Uhyve. This change introduces some additional background information and pointers for people looking to hack on the source code.
- Make "code blocks" more consistent
- Make some wording more consistent
- Additional Markdown magic
- Cut the length of some sentences
- Add `cargo run` method for developers
- Introduce GitHub-styled admonition boxes
=> README: Make it more beginner-friendly

.github/workflows/ci.yml, src/hypercall.rs, src/linux/x86_64/kvm_cpu.rs, src/macos/aarch64/vcpu.rs, src/macos/x86_64/vcpu.rs, tests/serial.rs, tests/test-kernels/Cargo.lock, tests/test-kernels/Cargo.toml, tests/test-kernels/src/bin/serial.rs, uhyve-interface/src/lib.rs, uhyve-interface/src/parameters.rs
Supersedes https://github.com/hermitcore/uhyve/pull/491
(Uhye-Interface was merged in the meantime, which made this PR requiring a rework)
=> Uart accept buffer

src/arch/x86_64/mod.rs, src/linux/x86_64/kvm_cpu.rs, tests/common.rs
Enhanced output formatting for pagetables & ensure that the `env_logger` is active in tests
=> Pretty printing & env logging

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/arch/aarch64/mod.rs, src/arch/x86_64/mod.rs, uhyve-interface/Cargo.toml, uhyve-interface/src/lib.rs
Minor updates, and actually, I've accidentally already published v0.1.2 on crates.io :sweat_smile:
=> Uhvye Interface v0.1.2

src/arch/x86_64/mod.rs, src/virtqueue.rs, uhyve-interface/src/lib.rs
I am praying to the Rust gods that this will work out.
=> style: fix clippy errors from 28-11-2024

src/arch/x86_64/mod.rs, src/arch/x86_64/paging/mod.rs, src/linux/gdb/section_offsets.rs, src/linux/x86_64/kvm_cpu.rs, src/macos/aarch64/vcpu.rs, src/macos/x86_64/vcpu.rs, src/mem.rs, src/vm.rs, tests/test-kernels/Cargo.lock
I'm pulling out some parts of https://github.com/hermit-os/uhyve/pull/725 to make that PR easier to understand/review/debug.
=> Use of GuestPhysAddr & added HugePageAlignedMem struct

README.md, img/vs_code.png
... this will be moved to the wiki for now.
=> docs(readme): move contributing instructions to wiki

CITATION.cff
=> Updated CITATION.cff

src/fdt.rs, src/vm.rs
See https://github.com/hermit-os/kernel/pull/1571.
Closes https://github.com/hermit-os/uhyve/issues/875.
=> feat(bootinfo): put TSC frequency into FDT

tests/common.rs, tests/fs-test.rs, tests/serial.rs, tests/test-kernels/Cargo.lock, tests/test-kernels/Cargo.toml
- Updated to Hermit 0.10.
- Initialize Logger in all tests
- Enhanced output checking
- Increased VM Memory to 64 MiB
Superseeds #867
=> Updated & refined tests

tests/panic.rs, tests/test-kernels/src/bin/panic.rs
=> Added panic integration test

Cargo.lock, Cargo.toml, data/aarch64/hello_world, src/arch/aarch64/mod.rs, src/bin/uhyve.rs, src/consts.rs, src/fdt.rs, src/linux/x86_64/kvm_cpu.rs, src/macos/aarch64/vcpu.rs, src/vcpu.rs, src/vm.rs, tests/gdb.rs
- fix bug in the initialization of vCPUs
- add GICv3 support, which requires macOS 15
- fix bug in the calculation of the physical address
=> improve macOS support

src/arch/aarch64/mod.rs
The arm64 MMU supports a contiguous bit which is a hint that the TTE is one of a set of contiguous entries which can be cached in a single TLB entry.
The contiguous bit should be only set if the page is mapped contiguous and each 16 KByte area have the same access property. Consequently, the first 16 KByte area doesn't use this bit because just the first page frame is mapped with the non-cacheable bit.
=> add support of contiguous bit

tests/common.rs, tests/fs-test.rs
Done with Landlock in mind, so as to not have Landlock restrictions leak from a recycled thread.
=> test(landlock): spawn new thread for fs tests

src/hypercall.rs, src/isolation/landlock.rs, src/linux/x86_64/kvm_cpu.rs, src/virtio.rs, src/vm.rs, tests/panic.rs, tests/serial.rs
See:
https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
=> chore: fix clippy warnings (05-05-2025)

tests/fs-test.rs
cherry-picked from https://github.com/hermit-os/uhyve/pull/1005
=> refactor(tests): use vec! to avoid unnecessary allocs

src/hypercall.rs, src/isolation/fd.rs, src/isolation/filemap.rs, src/isolation/landlock.rs, src/isolation/mod.rs, src/isolation/tempdir.rs, src/linux/x86_64/kvm_cpu.rs, src/params.rs, src/virtio.rs, src/vm.rs
Succeeds https://github.com/hermit-os/uhyve/pull/1005.
=> UhyveFileMap: Improve path/string handling and code style

src/bin/uhyve.rs
This will help us reuse existing structs by deriving the Deserialize trait later down the line (useful for #1013 and #1015) for configurations specific to individual machine images.
All entries under MemoryArgs, CpuArgs and GuestArgs are planned to be part of such configurations.
Arguments in UhyveArgs should not be exposed to machine image-specific configuration files. Assuming that these configuration files could very well be part of the machine image at a later point (which we consider to be untrusted), this makes the case of file_mapping particularly noteworthy (in the sense that it is an unsolvable problem): Although a machine image should not be able to use host filesystem locations, it could have the ability to declare guest filesystem locations. How this could be done is not …
=> refactor: categorize Args entries

README.md
See: https://github.com/hermit-os/kernel/pull/1831
=> docs(readme): replace hermit-playground with hermit-c

.github/workflows/ci.yml
Reverts hermit-os/uhyve#1031 :^)
=> Revert "ci: skip for markdown and image files"
