src/linux/mod.rs
src/linux/vcpu.rs
src/linux/virtio.rs

Added a PCI device framework and a simple virtio device. Currently it has no network capabilities, but is discoverable by libhermit-rs.
To be discoverable by libhermit-rs, the check if running on uhyve is removed for PCI.
This begins implementing #1.
To test, build using [this](https://github.com/hermitcore/libhermit-rs/pull/23) version of libhermit-rs. With HERMIT_VERBOSE set to 1, the expected output should show a virtio device under the PCI device information.

implemented simple virtio device framework

---

Cargo.toml
src/arch/x86.rs
src/debug_manager.rs
src/gdb_parser.rs
src/linux/gdb.rs
src/linux/i386-64bit.xml
src/linux/mod.rs
src/linux/uhyve.rs
src/linux/vcpu.rs
src/main.rs
src/utils.rs
src/vm.rs

Implements support for debugging with gdb and lldb:
Supported features:
- Register read/write
- Memory read/write
- Software breakpoints (int3)
- Hardware breakpoints
- Execute / Write / Read-Write
- Singlestepping / Continue
- LLDB support (transmit info about arch/reg layout)
- read of feature target.xml [i386-64bit.xml]
- qHostInfo triple sends x86_64-unknown-hermit
Support relies on two crates: gdb-protocol for an implementation of gdb-rsp packets sending/recving, and rust-gdb-remote-protocol for parsing the packets. The latter is included somewhat modified in gdb_parser.rs

Implement Debugging Support for single threads

---

.travis.yml
Cargo.lock
Cargo.toml
src/main.rs
src/vm.rs

Changes:
- Add CPU frequency detection via cpuid hypervisor detection method
- Add CPU frequency detection via parsing lscpu on linux. Tbis works on travis (ubuntu bionic)
- Refactored detect_freq_from_cpu_brand_string to work similar to new detection methods
- Add travis CI config to test if rusty-demo runs on top of uhyve.
Things to look at:
- Commit  d1e44b7 - VM Parse CPU frequency.... -> I find the code there to be a bit ugly since I wasn't able to use the `?` operator. I got errors saying that the cast from the specific error classes to `()` are not implemented. Is there any way to get around this? I would have thought that casting an Error to `()` would be trivial.

Improve cpu frequency detection

---

src/linux/vcpu.rs

- currently only the idle loop is using the hlt instruction
- if we ignore the instruction, the idle loop get computation times
=> is active waiting for a new task

ignore halt state => kernel switch in polling mode

---

.travis.yml

Print the version of rustc, cargo and rusty-hermit so that the information is in the logfile

CI: Print version of dependencies to logs

---

.gitattributes
Cargo.lock
Cargo.toml
benches/benchmarks.rs
benches/vm/mod.rs
benches_data/hello_world
src/lib.rs

Running `cargo bench` will check the performance of `vm.load_kernel()` for a
hello_world executable. `load_kernel()` seems to take the most cpu time when
starting an application.
Criterion can only be used with library crates and I created uhyvelib, which consists of an ugly c&p of parts of the `main.rs`. In an ideal world the uhyve binary would just use the lib, but I am not sure if it is worth the refactoring at the moment.

Provide initial Criterion.rs benchmark workspace

---

Cargo.lock
Cargo.toml
README.md
src/vm.rs

- just a workaround for issue #31 
- uhyve doesn't pass more the MAX_ENC variables to the unikernel

add check to pass not more than MAX_ENVC variables

---

Cargo.lock
Cargo.toml

While compiling uhyve, I noticed compiling Tokio, which takes a while.
Tokio is included in the dependency tree via the default `tokio` feature of `tun-tap`. As uhyve does not contain any `async` code, I disabled `tun-tap`'s default features, removing Tokio from the dependency tree.
The result should be noticeably faster compile times.
What do you think?
This is the dependency tree difference:
```diff
--- before	2020-09-21 10:25:46.766871951 +0200
+++ after	2020-09-21 10:25:38.547841407 +0200
@@ -89,145 +89,6 @@
│       │   └── unicode-xid v0.0.4
│       └── unicode-xid v0.0.4
├── tun-tap v0.1.2
-│   ├── futures v0.1.29
-│   ├── libc v0.2.76
-│   ├── mio v0.6.22
-│   │   ├── cfg-if v0.1.10
-│   │   ├── iovec v0.1.4
-│   │   │   └── libc v0.2.76
-│   │   ├── libc v0.2.76
-│   │   ├── log …
```

tun-tap: Exclude tokio dependencies

---

src/bin/uhyve.rs

The current uhyve argument parser does not specify that flags meant for uhyve should not be parsed following the kernel argument. Therefore, any argument to the kernel beginning with a hyphen is instead treated as an argument to uhyve, throwing an error. 
In other words: 
`uhyve kernel --verbose` currently parses the `--verbose` flag, enables the verbose setting in uhyve, and executes the kernel with **no arguments**. There is currently no way to give an argument to the kernel if it accepts a `--verbose` flag itself. This patch makes it so that the example command will instead pass the `--verbose` flag onto the kernel.
Note that this extends to any kernel argument beginning with a hyphen. If the user were to execute `uhyve kernel --foo`, uhyve would throw an error (since "foo" is not …

Allow kernel arguments to begin with a hyphen

---

src/macos/vcpu.rs
src/vm.rs

Currently, C-based applications (see [hermit-playground](https://github.com/hermitcore/hermit-playground)) are not relocatable. Consequently, the loader has to support relocatable and non-relocatable applications.

add support of non-relocatable binaries

---

Cargo.lock
Cargo.toml
src/linux/uhyve.rs

I came across deps.rs and saw that it lists outdated packages for uhyve: https://deps.rs/crate/uhyve/0.0.24

Fixed 3 clippy warnings + updated dependencies 

---

Cargo.lock
Cargo.toml
src/bin/uhyve.rs
src/error.rs
src/utils.rs

This uses the core_affinity crate to optionally bind the vCPU threads to a logical host CPU.
On MacOS this is apparently more of a hint.
The downside of using the core_affinity thread is that errors in `sched_setaffinity` are ignored. 
But since it appears to be working, I think this solution is fine for now. 
If I have some more time, maybe I'll use the libc functions directly and add appropriate error handling / reporting.
`-a` or `--affiity` takes a comma seperated list of logical CPUs or alternatively an inclusive range of logical CPUs.
Example `--affinity=1,3-5,9` would be valid and expands to the cpulist `1,3,4,5,9`.
The number of CPUs specified with `--affinity` must match the number specified with the `-c` option (default 1), otherwise an error is printed.
If `--affinity` is not …

Add --affinity option to bind CPU threads to a specified host CPU

---

src/bin/uhyve.rs
src/utils.rs

The first few commits clean up how hugepage support can be toggled from the Environment or via a parameter.
There was some mismatch between the name of the options and what it did, so the behaviour is now the following:
- `--disable-hugepages` now correctly disables hugepages. This overrides the Environment variable and any defaults
- `HERMIT_HUGEPAGE` now accepts True, true, False, false, Yes, yes, No, no and interprets them as boolean options. Additionally `HERMIT_HUGEPAGE=True` or `HERMIT_HUGEPAGE=1` now correctly enables hugepages.
Additionally the last commit attempts to detect support for transparent huge pages by parsing `sysfs`. This obviously is Linux only. A followup commit addressing MacOS is still required. @stlankes I'm leaning towards always enabling huge pages on MacOS. …

Improve Hugepage detection and parameters

---

src/linux/uhyve.rs

less VM exists should reduce the overhead

prevent VM exits due to the pause instructions

---

bors.toml

In uhyve the Job name for checking the formatting is called "Format check (ubuntu-latest, nightly)".
This should fix bors timing out.
cf name in:  https://github.com/hermitcore/uhyve/runs/1716087241

CI: Fix bors.toml status name

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
src/bin/uhyve.rs
src/linux/vcpu.rs
src/macos/vcpu.rs
src/vm.rs

Added `instrument` feature, which is disabled by default. It only works
if uhyve is compiled with `-Z instrument-mcount`. Furthermore I removed
the std::process::exit() call from uhyvelib so it is possible to write
the trace. The return value is not returned from `VirtualCPU::run()`.
Note that using rftrace may not be the best tool to trace uhyve as there
are various other tools available on a modern desktop OS, but can be
used to trace RustyHermit and using the same tool simplifies everything
a bit.

Added instrument feature using rftrace

---

.github/workflows/test.yml
coverage_rustcwrapper.sh
generate_test_coverage.sh
src/utils.rs

This is #53 again. Creating this again, so that bors works.
This PR mainly adds a script that automates test coverage report generation.
To generate the report the binaries is instrumented by setting the RUSTFLAG -Zinstrument-coverage which enables source-based coverage.
I've tested and this works for both unit and doctests (Master currently does not have any doctests, I verified it with a doctest I added locally).
The test coverage generated is specific to the architecture, i.e. the coverage report generated on a Linux machine will not consider any of the code which is for macOS and it won't appear in the reports.
However codecov.io automatically merges reports from different architectures, so the report, that the codecov bot will hopefully link below, should show a complete picture.

Add code Coverage reports

---

codecov.yml

Don't fail the `codecov/project` status if coverage drops by at most 1%. 
Since some lines in uhyve are sometimes compiled, but not covered, and sometimes not compiled at all, there
is a certain base fluctuation regarding the "missing" lines.

CI: Improve codecov project status

---

.github/workflows/test.yml
benches/benchmarks.rs
benches/complete_binary/mod.rs
benches_data/rusty-loader
benches_data/rusty_demo

This commit added 3 new benchmarks:
* running `rusty_demo` with uhyve
* running `hello_world` and `rusty_demo` with QEMU if QEMU is in $PATH
The QEMU benchmarks probably only work on a posix based system as
parsing $PATH expects `:` as the seperator between paths.
Fix #62

Add benchmarks using QEMU and rusty_demo

---

Cargo.lock
Cargo.toml
src/linux/vcpu.rs

- Bump kvm-bindings from 0.3.0 to 0.4.0 ([Release notes](https://github.com/rust-vmm/kvm-bindings/releases))
- Bump kvm-ioctls from 0.6.0 to 0.8.0 ([Release notes](https://github.com/rust-vmm/kvm-ioctls/releases))
- Bump vmm-sys-util from 0.7.0 to 0.8.0 ([Release notes](https://github.com/rust-vmm/vmm-sys-util/releases))
- Adjustments to support the new KVM bindings
- unwrap results of Msrs::from_entries to get MSR entries
- using KVM_MAX_CPUID_ENTRIES to define the maximum number of CPU entries

Bump kvm bindings

---

src/linux/vcpu.rs
src/macos/vcpu.rs
src/vm.rs

This avoids heap allocations and allows writing non-UTF-8-data to stdout.

Don't allocate when forwarding stdout

---

.github/workflows/kvm.yml

I suspect, the reason for [recent CI failures](https://github.com/hermitcore/uhyve/runs/2830867215#step:7:35) is that a KVM-CI-run did not complete and clean up after itself. So why not clean up, before cloning?

KVM-CI: Cleanup before cloning rusty-hermit

---

benches/complete_binary/mod.rs
benches/vm/mod.rs
src/arch/x86.rs
src/bin/uhyve.rs
src/error.rs
src/gdb_parser.rs
src/lib.rs
src/linux/gdb.rs
src/linux/uhyve.rs
src/linux/vcpu.rs
src/linux/virtio.rs
src/linux/virtqueue.rs
src/macos/gdb.rs
src/macos/ioapic.rs
src/macos/uhyve.rs
src/macos/vcpu.rs
src/utils.rs
src/vm.rs

Includes and supersedes  #117.

Fix Clippy warnings, adhere Rust 2018 idioms

---

.github/workflows/test.yml
generate_test_coverage.sh

Added command line arguments to skip some parts of the code. Also removed `rustfilt`

Refactored generate_coverage.sh script

---

Cargo.lock
Cargo.toml

This
1. Moves the binary source from `src/bin/uhyve.rs` to its standard location `src/main.rs`.
2. Renames the lib target from `uhyvelib` to its standard `uhyve`.
3. Reworks the `Cargo.toml` and updates `Cargo.lock`.

Rework Cargo.toml, update Cargo.lock

---

.github/workflows/test.yml
src/linux/mod.rs
src/vm.rs

Fixes https://github.com/hermitcore/uhyve/issues/151.
We can just opt out all tests that contain `test_vm`.

Remove has_vm_support

---

Cargo.lock
Cargo.toml
generate_test_coverage.sh
src/bin/uhyve.rs
src/error.rs
src/gdb_parser.rs
src/linux/gdb.rs
src/macos/gdb.rs
src/utils.rs

Binaries get a much smaller bin_utils and other helper functions are
replaced/moved.

Split up utils module

---

src/linux/vcpu.rs
src/macos/vcpu.rs
src/vm.rs

Factor out VirtualCPU::r#continue

---

.github/workflows/format.yml
.github/workflows/kvm.yml
.github/workflows/test.yml

This avoids version bumps for every minor update.

CI: Widen Actions version requirements

---

.github/workflows/clippy.yml
.github/workflows/format.yml
.github/workflows/kvm.yml
.github/workflows/test.yml

It is still required via bors.

CI: Don't run slow KVM tests on every PR

---

src/linux/mod.rs
src/linux/uhyve.rs
src/linux/virtio.rs
src/macos/mod.rs
src/macos/uhyve.rs
src/vm.rs

In https://github.com/hermitcore/uhyve/pull/164, I implement additional traits for `UhyveCPU` on linux, but not on macos.
To be able to use the trait impls, this makes the vCPU structs concrete instead of using trait objects.

Use concrete vCPU structs instead of trait objects

---

src/linux/uhyve.rs
src/macos/uhyve.rs
src/vm.rs

Access to section offsets is necessary for debugging (https://github.com/hermitcore/uhyve/pull/164).

Expose section offsets

---

benches/complete_binary/mod.rs
benches/vm/mod.rs
src/vm.rs
tests/common.rs

This fixes a faulty PathBuf construction and lets all PathBufs be constructed via collecting instead of pushing.

Improve path handling

---

.github/workflows/test.yml

This avoids GitHub check annotations about expected panics.
This reverts https://github.com/hermitcore/uhyve/commit/4e222b7ac023adff37b95d9e3790be4743d71f9a.

CI: Capture test output

---

.github/workflows/test.yml

This is required for the [`test_vm.*`](https://github.com/hermitcore/uhyve/blob/3b70087e3612e55ddce7888ce1b9fe91ca8596c9/src/vm.rs#L856-L907) to work correctly. Without this, they are not operating on the real files, but mere placeholders.
We need `git-lfs` to be installed on our runner for this.
Found via https://github.com/hermitcore/uhyve/pull/192.

CI: Download Git-LFS files

---

src/arch/x86_64/registers/debug.rs
src/linux/gdb/mod.rs

This fixes watchpoints in GDB (an oversight from https://github.com/hermitcore/uhyve/pull/164).
Found while working on integration tests, @jounathaen. ;)
bors r+

GDB: Correctly report stop reasons for watchpoints

---

tests/test-kernels/Cargo.toml

For easy integration tests of gdbstub, I need the `dev` `opt-level` to be 0.
On `release`, `opt-level` is 3 by default.

Integration tests: Use default profile

---

.github/workflows/test.yml
src/vm.rs

Depends on https://github.com/hermitcore/uhyve/pull/189 but is ready for review.
This ensures, that the intended error variant is returned.

mem_size tests: Assert exact error

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
tests/gdb.rs
tests/test-kernels/src/bin/gdb.rs

This depends on https://github.com/hermitcore/uhyve/pull/195, but is ready for review.

Add gdbstub integration test

---

Cargo.lock

Merging
1. https://github.com/hermitcore/uhyve/pull/211
2. https://github.com/hermitcore/uhyve/pull/205
in that order made the lockfile inconsistent.
bors r+

Fixup Cargo.lock

---

tests/test-kernels/rust-toolchain.toml

See
* https://github.com/hermitcore/rusty-hermit/pull/171

Integration tests: Upgrade to newer nightly channel

---

Cargo.toml
src/arch/x86_64/registers/debug.rs
src/bin/uhyve.rs
src/linux/gdb/mod.rs
src/linux/gdb/regs.rs
src/linux/uhyve.rs
src/linux/vcpu.rs
src/vm.rs

Depends on
* https://github.com/hermitcore/uhyve/pull/232 (because cargo on the integration tests parses the main Cargo.toml for some reason)

Upgrade to Rust 2021

---

src/vm.rs

See
* https://github.com/hermitcore/libhermit-rs/pull/311

BootInfo: Add tls_align

---

Cargo.toml

The dependency is already included conditionally on x86_64 platforms.

Cargo.toml: Remove superfluous `x86_64` dependency

---

.cargo/config.toml

This reverts commit a02f3421c0ff4e14561fac62d685be4d27847c99.
This removes the use of an unstable flag.

Revert "Linux: Use lld"

---

.github/workflows/test.yml

Closes https://github.com/hermitcore/uhyve/issues/212.
This depends on https://github.com/hermitcore/uhyve/issues/199 to be solved.

CI: Enable GDB integration test

---

Cargo.lock
Cargo.toml
src/macos/vcpu.rs

This is required for https://github.com/hermitcore/uhyve/issues/247.
The `x86` crate does not provide a configuration which can be compiled on the stable toolchain channel. The rest of uhyve has already been migrated to `x86_64`. The constants imported from `x86` have been inserted manually.

Remove x86 dependency

---

src/bin/uhyve.rs
src/utils.rs

madvise still works if hugepages are disabled system wide. It just does not have an effect then.

Hugepage: Don't check for system setting

---

Cargo.toml

I added @mkroening, @jbreitbart and @jounathaen as requested in https://github.com/hermitcore/uhyve/pull/263#issuecomment-1004375804.

Cargo.toml: Add authors

---

src/arch/aarch64/mod.rs
src/consts.rs
src/lib.rs
src/macos/aarch64/vcpu.rs
src/vm.rs

The hypercall was missing for MacOS on aarch64.

add missing implementation of the hypercall UHYVE_PORT_EXIT

---

src/linux/vcpu.rs
src/macos/aarch64/vcpu.rs
src/macos/x86_64/vcpu.rs
src/vm.rs

This PR moves the transmutes inside many `VirtualCPU` functions outside, moving the responsibility for a valid reference to the caller.

VirtualCPU: Take descriptive arguments

---

src/vm.rs

This was done correctly in caves uhyve: [`uhyve.c#L907`](https://github.com/hermitcore/hermit-caves/blob/e4b0302609c3bd47808bfc57f73178de32d90906/uhyve.c#L907)
Required for https://github.com/hermitcore/libhermit-rs/issues/506.

Correctly set possible_cpus

---

src/params.rs

Check for multiple of hugepagesize.
Related: #265

Improved memory size checking. 

---

tests/gdb.rs
tests/test-kernels/Cargo.lock
tests/test-kernels/Cargo.toml
tests/test-kernels/rust-toolchain.toml
tests/test-kernels/src/bin/create_file.rs
tests/test-kernels/src/bin/gdb.rs

```
Updating base64 v0.21.2 -> v0.21.6
Adding bitflags v2.4.1
Removing bumpalo v3.13.0
Updating cc v1.0.79 -> v1.0.83
Adding errno v0.3.8
Updating filetime v0.2.21 -> v0.2.23
Updating flate2 v1.0.26 -> v1.0.28
Updating form_urlencoded v1.2.0 -> v1.2.1
Adding getrandom v0.2.12
Adding hermit v0.8.0
Removing hermit-sys v0.5.4
Updating idna v0.4.0 -> v0.5.0
Removing js-sys v0.3.64
Updating libc v0.2.146 -> v0.2.152
Adding linux-raw-sys v0.4.12
Updating log v0.4.19 -> v0.4.20
Updating once_cell v1.18.0 -> v1.19.0
Updating percent-encoding v2.3.0 -> v2.3.1
Removing proc-macro2 v1.0.60
Removing quote v1.0.28
Updating redox_syscall v0.2.16 -> v0.4.1
Updating ring v0.16.20 -> v0.17.7
Adding rustix v0.38.28
Updating rustls v0.21.2 -> v0.21.10
Updating rustls-webpki v0.100.1 -> v0.101.7
Updating sct …
```

test: update test kernels to hermit 0.8

---

.github/workflows/ci.yml

Closes https://github.com/hermitcore/uhyve/pull/457.
I think it might make sense for us to decide that we do not want to test upstream kernels in CI and instead use a pre-built image. See https://github.com/hermitcore/uhyve/pull/457#issuecomment-1379450088.

CI: Run pre-built rusty_demo instead of building upstream

---

.github/workflows/ci.yml

Host panics may cause in Uhyve not terminating: https://github.com/hermit-os/uhyve/actions/runs/7963339605/job/21738698422

ci: add timeout for running images

---

src/linux/x86_64/kvm_cpu.rs

QEMU and Firecracker don't panic here either.
With this, `hermit::arch::x86_64::shutdown` from https://github.com/hermit-os/kernel/pull/1181 would also work on Uhyve, though proper exits via system calls still go through the exit hypercall.

fix(x86_64): don't panic on unknown port

---

.github/workflows/ci.yml
.github/workflows/release.yml

Because of time constraints and because the workflow itself may need some additional work to support multiple operating systems without making individual releases for every target architecture and operating system, builds are only generated for Linux (amd64).
New releases are marked as "Drafts" by default, so as to allow maintainers to edit the text before publication.
Fixes https://github.com/hermit-os/uhyve/issues/256

CI: Publish binaries using GitHub Actions on new tag

---

README.md
src/arch/aarch64/mod.rs
tests/common.rs
uhyve-interface/src/elf.rs
uhyve-interface/src/lib.rs

Based on https://github.com/hermit-os/uhyve/pull/689
Fixes https://github.com/hermit-os/uhyve/issues/458
Closes https://github.com/hermit-os/uhyve/pull/689

docs: capitalize Uhyve

---

src/vm.rs

There was an idea to initialize the mmap using different guest_address parameters.
Despite how most of the code is already "future-proofed", with a clear intention of heading towards that direction and `vm.rs` using `self.mem.guest_address` everywhere (despite that value currently being equal to zero), this change modifies a small exception to that rule.

vm.rs: Replace hardcoded arch::RAM_START in BootInfo

---

.github/workflows/ci.yml

Could be useful in some cases when GitHub Actions fails on a specific target.

CI: Enable RUST_BACKTRACE for tests

---

README.md

- "Visual Code" is a typo
- instructions are not Visual Studio Code specific
- Add URLs to the projects' respective pages (purely cosmetic)

docs(readme): fix and improve VS Code mention

---

Cargo.lock
uhyve-interface/Cargo.toml
uhyve-interface/src/lib.rs

It was almost impossible to use this fn before, as it takes the ownership of the whole struct, making access to the data impossible. 
This was a mistake in the first place and should now be resolved.

uhyve-interface: Don't take ownership on fn port()

---

Cargo.lock
Cargo.toml
src/bin/uhyve.rs
src/consts.rs
src/fdt.rs
src/hypercall.rs
src/lib.rs
src/params.rs
src/vm.rs
uhyve-interface/src/parameters.rs

Depends on Kernel PR: https://github.com/hermit-os/kernel/pull/1394
CI should be fixed by https://github.com/hermit-os/kernel/pull/1396.

feat: put memory and env vars into FDT

---

tests/test-kernels/rust-toolchain.toml

Result of the investigation behind the failing tests (https://github.com/hermit-os/uhyve/issues/726), however, this doesn't actually fix anything.

test: update toolchain channel to `nightly-2024-09-01`

---

tests/test-kernels/Cargo.lock

chore: fix test-kernel's `Cargo.lock`

---

src/params.rs

Required for https://github.com/hermit-os/uhyve/pull/786.

fix(params): ambiguous reference to positional arguments

---

.github/workflows/ci.yml
README.md
src/bin/uhyve.rs
src/hypercall.rs
src/linux/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/macos/mod.rs
src/macos/x86_64/vcpu.rs
src/params.rs
src/vm.rs
tests/common.rs
tests/gdb.rs
tests/serial.rs

- Removed `-v`/`--verbose` flag to fix #496 
- Add output capture mechanism. resolves #528

Reworked uhyve output

---

tests/common.rs
tests/fs-test.rs
tests/serial.rs

This should help us keep up with the increasing complexity of the tests (including for features currently being developed). verify_file_equals is not particularly useful right now, but I intend on using it more intensively for the UhyveFileMap feature much more extensively.

test: add fs-related helper functions

---

Cargo.lock
Cargo.toml
README.md
src/bin/uhyve.rs
src/consts.rs
src/hypercall.rs
src/isolation.rs
src/lib.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/macos/x86_64/vcpu.rs
src/params.rs
src/vm.rs
tests/common.rs
tests/data/fixtures/fs/README.md
tests/data/fixtures/fs/this_folder_exists/file_in_folder.txt
tests/data/fixtures/fs/this_symlink_is_dangling
tests/data/fixtures/fs/this_symlink_is_valid
tests/data/fixtures/fs/this_symlink_leads_to_a_file
tests/fs-test.rs
tests/serial.rs
tests/test-kernels/Cargo.toml
tests/test-kernels/src/bin/open_close_file.rs
uhyve-interface/src/parameters.rs

* Add UhyveFileMap structure that maps guest and host paths, unit tests
* Add integration tests and unit tests
* Sandbox `uhyvelib::hypercall::open` and `uhyvelib::hypercall:unlink`
Fixes https://github.com/hermit-os/uhyve/issues/767, https://github.com/hermit-os/uhyve/issues/239

Create sandbox for host file system access

---

src/isolation.rs

This turns host paths that do not exist yet into absolute paths. Doing something similar for the guest paths is also a TODO.

feat(isolation): improve canonicalization of host paths

---

src/hypercall.rs

See 'https://rust-lang.github.io/rust-clippy/master/index.html#needless_as_bytes'

nit(hypercall): remove unnecessary .as_bytes() call

---

src/hypercall.rs
src/isolation/filemap.rs
src/isolation/mod.rs
src/isolation/tempdir.rs
src/vm.rs

This is a form of preparation for the introduction of additional security-related measures, which may be best to implement in separate files.

refactor: split isolation.rs into files

---

src/hypercall.rs
src/isolation/filemap.rs
src/isolation/tempdir.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/macos/x86_64/vcpu.rs
src/vm.rs

This aims to reduce coupling between UhyveVm, the hypercalls and crate::isolation::tempdir.
Fixes #818.

feat(isolation): move tempdir functionality to UhyveFileMap

---

README.md

Closes https://github.com/hermit-os/uhyve/issues/837.
This was introduced in https://github.com/hermit-os/uhyve/commit/0384c1d050057035d892e2b52f825a4be4bc73a7.

docs(readme): fix configuration section

---

README.md

docs(readme): change tagline, condense information

---

src/bin/uhyve.rs

It makes sense to group it togehter with output and stats, instead of pushing it all the way down beneath the Memory and Cpu help headings. We presume that the settings under those headings to be more "optional" than --file-mapping, as the defaults do not have to be changed very often.

nit(cli): move file_mapping further up in Args

---

src/hypercall.rs
uhyve-interface/src/parameters.rs

Just spotted this unfortunate error, oops.

fix(hypercall): use sanitized flags for mapped files

---

src/linux/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/macos/mod.rs
src/macos/x86_64/vcpu.rs
src/vm.rs

I don't particularly like this, as the functions of the sealed trait are still visible, but it is at least better than before.

Use sealed trait pattern to avoid private trait in public interface warning

---

benches/vm/mod.rs
src/arch/x86_64/mod.rs
src/hypercall.rs
src/linux/gdb/breakpoints.rs
src/linux/gdb/mod.rs
src/linux/gdb/section_offsets.rs
src/linux/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/macos/mod.rs
src/macos/x86_64/vcpu.rs
src/serial.rs
src/vcpu.rs
src/vm.rs

Unfortunately, fixing this requires a complete refactoring of the current code, as we need present vcpus to query KVM for the correct TSC frequency.
Fixes #862

Fix TSC frequency.

---

src/arch/x86_64/mod.rs
src/lib.rs
src/linux/gdb/mod.rs
src/linux/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/mod.rs
src/virtio.rs
src/virtqueue.rs
src/vm.rs

There are many components marked `pub` in uhyvelib that are actually not meant to be exposed. This is not only bad design, but also prevents `dead_code` lints. This is an attempt to fix this partly

Removed unwanted `pub` from uhyvelib

---

src/linux/x86_64/kvm_cpu.rs
src/mem.rs

Fixed incorrect bounds check and allow MMIO writes to `0x9_F000..0xA_0000 | 0xF_0000..0x10_0000`, which is the location of the MP floating table and might cause exits, once there is no real memory backing for these addresses.

Minor fixes

---

src/bin/uhyve.rs
src/params.rs

Reordered clap arguments and improved `GuestMemorySize` printing

Slight Clap help text improvements

---

src/bin/uhyve.rs
src/hypercall.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/params.rs
src/vm.rs
tests/env.rs
tests/test-kernels/src/bin/env.rs

Invocation: `uhyve -e HOST=myhost -e "ASDF=lkj"  mykernel`.

Added selective environment passing for VM.

---

Cargo.lock
Cargo.toml
src/arch/aarch64/mod.rs
src/arch/x86_64/mod.rs
src/arch/x86_64/paging/mod.rs
src/bin/uhyve.rs
src/consts.rs
src/hypercall.rs
src/linux/gdb/breakpoints.rs
src/linux/gdb/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/paging.rs
src/params.rs
src/vm.rs
tests/gdb.rs

- Move x86_64-related paging code to src/arch/x86_64/paging
- Tests: x86_64-related paging tests should use a guest_address that is
not 0
- Tests: Move them in separate files, use appropriate 'use' directives
- Tests: Use init_guest_mem wrapper in test_virt_to_phys
- Fix kernel memory loading
- Add guest_address getter in UhyveVm
- Change names of constants to clarify their purpose
- Remove pagetable_l0 from virt_to_phys function
- Various `cargo fmt`-related changes
- aarch64: Blindly replace constant names and similar RAM_START change
We currently rely on guest_address in MmapMemory to calculate the
offsets during the initialization of the VM and when converting
virtual addresses to physical addresses. The latter case is intended
to be temporary - we should read the value from the CR3 …

ASLR support

---

tests/fs-test.rs
tests/test-kernels/src/bin/remove_file.rs

More tests for hypercalls

---

src/linux/x86_64/kvm_cpu.rs

Added APICBASE MSR

---

.github/workflows/ci.yml
Cargo.lock
tests/test-kernels/Cargo.lock

The second commit fixes https://github.com/hermit-os/uhyve/security/dependabot/12.

build(deps): update Cargo.lock

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
rust-toolchain.toml
tests/common.rs
tests/gdb.rs

This prepares https://github.com/hermit-os/uhyve/pull/748, which we don't want to merge right now.

ci: prepare running KVM jobs on GitHub runners

---

src/arch/aarch64/mod.rs

This fixes a new Clippy lint from Rust 1.85.

fix(aarch64): `clippy::precedence`

---

src/bin/uhyve.rs
src/hypercall.rs

This is required for upgrading time to 0.3.40, which pulls deranged 0.4.0, which also implements TryFrom for most of these comparisons.
See https://github.com/hermit-os/uhyve/pull/932.

fix: provide type annotations in comparisons

---

src/linux/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/vcpu.rs
src/vm.rs
tests/gdb.rs

- renamed `init` -> `thread_local_init`
- call "normal" init for x86_64::kvm_cpu during `new`. This fixes an GDB
initialization issue, where virtual addresses were queried before the
CR3 register was set.
- removed `vcpu_init` fn, as initialization is now called either in
`new` or in `run`.
- call thread_local_initialization in `run_gdb` for linux. Currently
this has no effect, but probably enhances consistency.

Enhanced & fixed CPU initialization

---

src/arch/aarch64/mod.rs
src/arch/x86_64/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/paging.rs
src/vm.rs

- The Global Interrupt Controller is configured at address 0x8000000. To avoid conflicts, the starting address of the main memory is move to an higher address.
- In addition, a bug in the initialization of the page tables is removed. The calculation of the page table indices was wrong.
- Improve debug messages
- Remove typos in comments
- Like the Hermit loader, the cache is now disabled for I/O devices.
- close #949

aarch64: fix bug in the initialization of the page tables

---

src/fdt.rs
src/vm.rs

Without this devicetree node, Hermit will not configure the interrupt handler for the timer interrupt.

encode the timer configuration in the devicetree

---

Cargo.toml
src/hypercall.rs
src/isolation/fd.rs
src/isolation/filemap.rs
src/isolation/mod.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
tests/fs-test.rs
tests/test-kernels/src/bin/open_remove_close_file.rs
tests/test-kernels/src/bin/open_remove_close_remove_file.rs
tests/test-kernels/src/bin/open_remove_remove_close_file.rs
tests/test-kernels/src/bin/write_to_fd.rs
uhyve-interface/src/parameters.rs

This extends UhyveFileMap with a sandbox mapping file descriptors to maps, so as to prevent the opening of file descriptors that belong to Uhyve (or to that of other VMs, when Uhyve exposes such functionality to the user).
This change also introduces a series of test cases for the sandbox, including close / unlink, as well as tests that deliberately use invalid or leaked file descriptors.

feat(sandbox): add fd sandbox

---

src/hypercall.rs

fix(hypercall): Fix missing return on invalid open() flags

---

src/bin/uhyve.rs
src/fdt.rs
src/linux/x86_64/kvm_cpu.rs
src/macos/aarch64/vcpu.rs
src/mem.rs

Some warnings involving #[deny(clippy::mut_from_ref)] still not fixed.

chore: fix some clippy warnings (27-06-2025)

---

src/arch/aarch64/mod.rs
src/arch/x86_64/paging/mod.rs
src/macos/aarch64/vcpu.rs
src/mem.rs
src/vcpu.rs
src/virtio.rs
src/virtqueue.rs
src/vm.rs
tests/common.rs

This is done anywhere apart from architecture-specific and test code. Some unnecessary attributes were discovered and removed as well.
Reasons were added to all found instances of allow attributes, although we cannot enforce this only for allow using clippy::allow_attributes_without_reason as this lint affects both allow and expect attributes.
An attribute that explicitly allows the allow attribute was added for src/arch/mod.rs and tests/common.rs, as using allow is totally fine there. Nevertheless, I added reasons for allow attributes inside of the tests, because more documentation can't hurt (and we were already doing this for a gdb function).

chore: prefer expect attr and reasons

---

.github/workflows/ci.yml

This prevents unnecessary CI runs if the files themselves don't actually need to be checked using the CI. Mostly useful for doc updates.

ci: skip for markdown and image files

---

Cargo.lock
Cargo.toml
data/sample_config.toml
src/bin/uhyve.rs
src/params.rs

This adds support for machine image-independent configuration files for Uhyve. Certain machine-dependent parameters, such as file mapping, kernel arguments and kernel have been omitted for starters.
The Deserialization code for Affinity was a contribution by Ellen (@fogti) with minor adjustments.

feat: add TOML configuration for Uhyve

---

Cargo.lock
Cargo.toml
src/bin/uhyve.rs

Fixes #1035
by decoupling Affinity::from_str from validation
(instead, validation is moved into Affinity::validate)
Fixes #1036
by incorporating the refactored code written earlier.

fix(bin/uhyve): improve `Affinity` parsing

---

src/params.rs

tested on `nightly-2025-08-07-x86_64-unknown-linux-gnu`
precise behavioral change not tested in great detail, but it doesn't seem like the affected LoC could fall e.g. under https://github.com/rust-lang/rust-clippy/issues/15335

nit(params): fix clippy::manual_is_multiple_of

---

src/bin/uhyve.rs
src/linux/mod.rs

GDB connections will be waited for in a v4 and a v6 localhost socket, while not using 'localhost' itself. Doing so causes issues e.g. in atomic Fedora distributions (inside of a containerized toolbox environment).
Further: The 'feature' of choosing a random port is actually a workaround to a bug: Before, the user would have been able to select 0 (as allowed by TcpListener::bind), and this would have been fine. However, Uhyve would report that it is awaiting a connection on port 0, when it is actually listening on another port. I found exposing TcpListener's functionality to the user cooler than trying to impose restrictions, but this will presumably not be of use to anyone, really.

feat(gdb): don't rely on resolving localhost, choose random port if no port is set

---

src/bin/uhyve.rs
src/isolation/landlock.rs

This is a WIP: This still doesn't work because of linker-related issues which I am not sure how to fix right now. I presume that this broke because we do not test for `--all-features` (including the `instruments` feature).

fix(rftrace): fix parameters, allow static mut refs
